model:
  path: "keyword_spotting/weights/checkpoint.tflite"
  confidence: 0.5
  labels: ["background", "marvin"]
  infer_hop_samples: 3200
  inference_rate: 1.0
ros:
  publish_topic: "/voice/command"
  inference_topic: "/voice/inference"
  publish_inference: true
  audio_topic: "/audio/raw"
  input_sample_rate: 48000
  force_input_sample_rate: 48000
  audio_channels: 2
  sample_width_bytes: 4
  s32_shift_bits: 0
  audio_channel_index: -1
  audio_gain: 5.0
debug:
  save_detected_chunks: true
  detected_chunk_dir: "detected_chunks"
  record_audio_chunks: true
  audio_chunk_dir: "audio_chunks"
  audio_chunk_seconds: 5.0
  record_raw_audio_chunks: true
  raw_audio_chunk_dir: "raw_audio_chunks"
  raw_audio_chunk_seconds: 5.0
